name: "PR Analytics"

on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report start date (d/MM/yyyy)"
        required: true
      report_date_end:
        description: "Report end date (d/MM/yyyy)"
        required: true

jobs:
  create-report:
    name: "Create PR analytics report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run PR analytics"
        uses: AlexSim93/pull-request-analytics-action@v4.6.0
        with:
          GITHUB_TOKEN: ${{ secrets.MY_PAT_TOKEN }}
          GITHUB_OWNER_FOR_ISSUE: sharmatanikesh
          GITHUB_REPO_FOR_ISSUE: calculator
          GITHUB_OWNERS_REPOS: |
            sharmatanikesh/calculator
          EXECUTION_OUTCOME: markdown,new-issue
          CORE_HOURS_START: "9:00"
          CORE_HOURS_END: "19:00"
          TIMEZONE: "Asia/Kolkata"
          USE_CHARTS: true
          SHOW_CORRELATION_GRAPHS: true
          SHOW_ACTIVITY_TIME_GRAPHS: true
          AGGREGATE_VALUE_METHODS: percentile,average,median,sum,min,max
          SHOW_STATS_TYPES: timeline,workload,pr-quality,code-review-engagement,response-time
          REVIEW_TIME_INTERVALS: 4,8,12
          APPROVAL_TIME_INTERVALS: 4,8,12
          MERGE_TIME_INTERVALS: 4,8,12
          TOP_LIST_AMOUNT: 5
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
